#include <stdio.h>
#include <Windows.h>		//WinAPI
#include <mmsystem.h>
#include "functionheader.h"
#include "resource.h"

#pragma comment(lib, "winmm.lib")					//PlaySound 함수 호출을 위한 winmm.lib 라이브러리를 로드합니다.

void stillalive(void)
{
	system("title Still Alive");					// CMD 제목
	system("mode con cols=95 lines=38");			// 가로 110, 세로 40
	textcolor(14);									// 글자색: 노란색

	timeBeginPeriod(1);		// 주기를 1ms로 설정

	/* PlaySound 함수를 호출한다. 플래그로는 SND_FILENAME(첫번째 매개변수를 파일명으로 인식), SND_ASYNC(비동기적으로 재생)을
	사용하며 원하는 플래그들을 OR로 연결한다. */
	PlaySound(MAKEINTRESOURCE(IDR_WAVE1), NULL, SND_RESOURCE | SND_ASYNC);

	// 자막
	//-------------------------------------------------------------------------------------------------------
	Sleep(505);
	printf("T");					// This was a triumph.
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf(".\n");
	Sleep(2600);					// I'm making a note here: HUGE SUCCESS.
	printf("I");
	Sleep(30);
	printf("'");
	Sleep(30);
	printf("m");
	Sleep(30);
	printf(" ");
	Sleep(30);
	printf("m");
	Sleep(30);
	printf("a");
	Sleep(30);
	printf("k");
	Sleep(30);
	printf("i");
	Sleep(30);
	printf("n");
	Sleep(30);
	printf("g");
	Sleep(30);
	printf(" ");
	Sleep(30);
	printf("a");
	Sleep(30);
	printf(" ");
	Sleep(30);
	printf("n");
	Sleep(30);
	printf("o");
	Sleep(30);
	printf("t");
	Sleep(30);
	printf("e");
	Sleep(30);
	printf(" ");
	Sleep(30);
	printf("h");
	Sleep(30);
	printf("e");
	Sleep(30);
	printf("r");
	Sleep(30);
	printf("e");
	Sleep(30);
	printf(":");
	Sleep(30);
	printf(" ");
	Sleep(1300);
	printf("H");
	Sleep(60);
	printf("U");
	Sleep(60);
	printf("G");
	Sleep(60);
	printf("E");
	Sleep(60);
	printf(" ");
	Sleep(300);
	printf("S");
	Sleep(60);
	printf("U");
	Sleep(60);
	printf("C");
	Sleep(60);
	printf("C");
	Sleep(60);
	printf("E");
	Sleep(60);
	printf("S");
	Sleep(60);
	printf("S");
	Sleep(60);
	printf(".\n");
	Sleep(2000);					// It's hard to overstate my satisfaction.
	printf("i");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("n \n");
	Sleep(4810);

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,                ");
	puts("               . :H@@@MM@M#H/.,+%;,           ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,        ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-      ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.    ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.   ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;   ");
	puts("      =-./@M@M$                  .;@MMMM@MM:  ");
	puts("      X@/ -$MM/                    .+MM@@@M$  ");
	puts("     ,@M@H: :@:                    . =X#@@@@- ");
	puts("     ,@@@MMX, .                    /H- ;@M@M= ");
	puts("     .H@@@@M@+,                    %MM+..%#$. ");
	puts("      /MMMM@MMH/.                  XM@MH; =;  ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,   ");
	puts("        .=--------.           -%H.,@@@@@MX,   ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.    ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=      ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=        ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,          ");
	puts("                    =++%%%%+/:-.              ");
	textcolor(14);
	gotoxy(0, 5);

	printf("A");					//Apeture Science:
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("S");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(": \n");
	Sleep(3050);
	printf("W");					//We do what we must because we can
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf(". \n");
	Sleep(3200);
	printf("F");					// For the good of all of us.
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("s \n");
	Sleep(1650);

	gotoxy(0, 14);
	puts("                  =+$HM####@H%;,              ");
	puts("               /H###############M$,           ");
	puts("               ,@################+            ");
	puts("                .H##############+             ");
	puts("                  X############/              ");
	puts("                   $##########/               ");
	puts("                    %########/                ");
	puts("                     /X/;;+X/                 ");
	puts("                      -XHHX-                  ");
	puts("                     ,######,                 ");
	puts("     #############X  .M####M.  X############# ");
	puts("     ##############-   -//-   -############## ");
	puts("     X##############%,      ,+##############X ");
	puts("     -##############X        X##############- ");
	puts("      %############%          %############%  ");
	puts("       %##########;            ;##########%   ");
	puts("        ;#######M=              =M#######;    ");
	puts("         .+M###@,                ,@###M+.     ");
	puts("            :XH.                  .HX:        ");
	puts("                                              ");
	gotoxy(0, 8);

	printf("E");					//Except the ones who are dead
	Sleep(60);
	printf("x");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(". \n");
	Sleep(500);
	system("cls");

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,                ");
	puts("               . :H@@@MM@M#H/.,+%;,           ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,        ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-      ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.    ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.   ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;   ");
	puts("      =-./@M@M$                  .;@MMMM@MM:  ");
	puts("      X@/ -$MM/                    .+MM@@@M$  ");
	puts("     ,@M@H: :@:                    . =X#@@@@- ");
	puts("     ,@@@MMX, .                    /H- ;@M@M= ");
	puts("     .H@@@@M@+,                    %MM+..%#$. ");
	puts("      /MMMM@MMH/.                  XM@MH; =;  ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,   ");
	puts("        .=--------.           -%H.,@@@@@MX,   ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.    ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=      ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=        ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,          ");
	puts("                    =++%%%%+/:-.              ");
	textcolor(14);
	gotoxy(0, 0);

	Sleep(200);					//But there's no sense crying over every mistake
	printf("B");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("e \n");
	Sleep(1200);
	printf("Y");					// you just keep on trying till you run out of cake
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("j");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("e \n");

	gotoxy(0, 14);
	puts("                      =/;;/-                  ");
	puts("                     +:    //                 ");
	puts("                    /;      /;                ");
	puts("                   -X        H.               ");
	puts("     .//;;;:;;-,   X=        :+   .-;:=;:;%;. ");
	puts("     M-       ,=;;;#:,      ,:#;;:=,       ,@ ");
	puts("     :%           :%.=/++++/=.$=           %= ");
	puts("      ,%;         %/:+/;,,/++:+/         ;+.  ");
	puts("        ,+/.    ,;@+,        ,%H;,    ,/+,    ");
	puts("           ;+;;/= @.  .H##X   -X :///+;       ");
	puts("           ;+=;;;.@,  .XM@$.  =X.//;=%/.      ");
	puts("        ,;:      :@%=        =$H:     .+%-    ");
	puts("      ,%=         %;-///==///-//         =%,  ");
	puts("     ;+           :%-;;;:;;;;-X-           +: ");
	puts("     @-      .-;;;;M-        =M/;;;-.      -X ");
	puts("      :;;::;;-.    %-        :+    ,-;;-;:==  ");
	puts("                   ,X        H.               ");
	puts("                    ;/      %=                ");
	puts("                     //    +;                 ");
	puts("                      ,////,                  ");
	gotoxy(0, 2);

	Sleep(1110);
	printf("A");					// and then science gets done and you make a neat gun
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("n \n");

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,                ");
	puts("               . :H@@@MM@M#H/.,+%;,           ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,        ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-      ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.    ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.   ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;   ");
	puts("      =-./@M@M$                  .;@MMMM@MM:  ");
	puts("      X@/ -$MM/                    .+MM@@@M$  ");
	puts("     ,@M@H: :@:                    . =X#@@@@- ");
	puts("     ,@@@MMX, .                    /H- ;@M@M= ");
	puts("     .H@@@@M@+,                    %MM+..%#$. ");
	puts("      /MMMM@MMH/.                  XM@MH; =;  ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,   ");
	puts("        .=--------.           -%H.,@@@@@MX,   ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.    ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=      ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=        ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,          ");
	puts("                    =++%%%%+/:-.              ");
	textcolor(14);
	gotoxy(0, 3);

	Sleep(1100);
	printf("F");					// for the people who are still alive.
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(". \n");
	Sleep(4700);
	system("cls");

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,               ");
	puts("               . :H@@@MM@M#H/.,+%;,          ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,       ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-     ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.   ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.  ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;  ");
	puts("      =-./@M@M$                  .;@MMMM@MM: ");
	puts("      X@/ -$MM/                    .+MM@@@M$ ");
	puts("     ,@M@H: :@:                    . =X#@@@@-");
	puts("     ,@@@MMX, .                    /H- ;@M@M=");
	puts("     .H@@@@M@+,                    %MM+..%#$.");
	puts("      /MMMM@MMH/.                  XM@MH; =; ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,  ");
	puts("        .=--------.           -%H.,@@@@@MX,  ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.   ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=     ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=       ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,         ");
	puts("                    =++%%%%+/:-.             ");
	textcolor(14);
	gotoxy(0, 0);

	Sleep(2550);
	printf("I");					// i'm not even angry
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf(". \n");
	Sleep(3100);
	printf("I");					//i'm being so
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(800);
	printf("s");					//sincere right now.
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf(". \n");
	Sleep(2600);
	printf("E");					//even though you rboke my heart and killed me
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(". \n");

	gotoxy(0, 14);
	puts("                               .,---.        ");
	puts("                             ,/XM#MMMX;,     ");
	puts("                           -%##########M%,   ");
	puts("                          -@######%  $###@=  ");
	puts("           .,--,         -H#######$   $###M: ");
	puts("        ,;$M###MMX;     .;##########$;HM###X=");
	puts("      ,/@##########H=      ;################+");
	puts("     -+#############M/,      %##############+");
	puts("     %M###############=      /##############:");
	puts("     H################      .M#############;.");
	puts("     @###############M      ,@###########M:. ");
	puts("     X################,      -$=X#######@:   ");
	puts("     /@##################%-     +######$-    ");
	puts("     .;##################X     .X#####+,     ");
	puts("      .;H################/     -X####+.      ");
	puts("        ,;X##############,       .MM/        ");
	puts("           ,:+$H@M#######M#$-    .$$=        ");
	puts("                .,-=;+$@###X:    ;/=.        ");
	puts("                       .,/X$;   .::,         ");
	puts("                           .,    ..          ");
	gotoxy(0, 3);

	Sleep(3900);
	printf("A");					// and tore me to peices.
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(". \n");

	gotoxy(0, 14);
	puts("                 .+                          ");
	puts("                  /M;                        ");
	puts("                   H#@:              ;,      ");
	puts("                   -###H-          -@/       ");
	puts("                    %####$.  -;  .%#X        ");
	puts("                     M#####+;#H :M#M.        ");
	puts("     ..          .+/;%#########X###-         ");
	puts("      -/%H%+;-,    +##############/          ");
	puts("         .:$M###MH$%+############X  ,--=;-   ");
	puts("             -/H#####################H+=.    ");
	puts("                .+#################X.        ");
	puts("              =%M####################H;.     ");
	puts("                 /@###############+;;/%%;,   ");
	puts("              -%###################$.        ");
	puts("            ;H######################M=       ");
	puts("         ,%#####MH$%;+#####M###-/@####%      ");
	puts("       :$H%+;=-      -####X.,H#   -+M##@-    ");
	puts("      .              ,###;    ;      =$##+   ");
	puts("                     .#H,               :XH, ");
	puts("                      +                   .;-");
	gotoxy(0, 4);

	Sleep(2900);
	printf("A");					// and threw every piece
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(550);
	printf("i");					//into
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(650);
	printf("a");					// a fire
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".");

	gotoxy(0, 14);
	puts("                          -$-                ");
	puts("                         .H##H,              ");
	puts("                        +######+             ");
	puts("                     .+#########H.           ");
	puts("                   -$############@.          ");
	puts("                 =H###############@  -X:     ");
	puts("               .$##################:  @#@-   ");
	puts("          ,;  .M###################;  H###;  ");
	puts("        ;@#:  @###################@  ,#####: ");
	puts("      -M###.  M#################@.  ;######H ");
	puts("      M####-  +###############$   =@#######X ");
	puts("      H####$   -M###########+   :#########M, ");
	puts("       /####X-   =########%   :M########@/.  ");
	puts("         ,;%H@X;   .$###X   :##MM@%+;:-      ");
	puts("                      ..                     ");
	puts("       -/;:-,.              ,,-==+M########H ");
	puts("      -##################@HX%%+%%$%%%+:,,    ");
	puts("        .-/H%%%+%%$H@###############M@+=:/+:");
	puts("     /XHX%:#####MH%=    ,---:;;;;/%%XHM,:###$");
	puts("     $@#MX %+;-                           .  ");
	gotoxy(0, 5);

	Sleep(2250);
	printf("A");					//as they burnt it hurt because
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("e ");
	Sleep(1450);
	printf("I");					// i was so happy for you.
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf(".");

	gotoxy(0, 14);
	textcolor(10);
	puts("                                          :X-");
	puts("                                       :X### ");
	puts("                                     ;@####@ ");
	puts("                                   ;M######X ");
	puts("                                 -@########$ ");
	puts("                               .$##########@ ");
	puts("                              =M############-");
	puts("                             +##############$");
	puts("                           .H############$=. ");
	puts("              ,/:         ,M##########M;.    ");
	puts("           -+@###;       =##########M;       ");
	puts("        =%M#######;     :#########M/         ");
	puts("     -$M###########;   :#########/           ");
	puts("      ,;X###########; =########$.            ");
	puts("          ;H#########+#######M=              ");
	puts("            ,+##############+                ");
	puts("               /M#########@-                 ");
	puts("                 ;M######%                   ");
	puts("                   +####:                    ");
	puts("                    ,$M-                     ");
	textcolor(14);
	gotoxy(0, 7);

	Sleep(800);
	printf("\nN");					// now these points of data make a beautiful line
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("e\n");
	Sleep(1300);
	printf("A");					// and we're out of beta we're releasing on time
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".\n");
	Sleep(1250);
	printf("S");					// so i'm GLaD i got burned think of all the things we learned
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("G");
	Sleep(60);
	printf("L");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("D");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("d");

	gotoxy(0, 14);
	puts("                 .+                          ");
	puts("                  /M;                        ");
	puts("                   H#@:              ;,      ");
	puts("                   -###H-          -@/       ");
	puts("                    %####$.  -;  .%#X        ");
	puts("                     M#####+;#H :M#M.        ");
	puts("     ..          .+/;%#########X###-         ");
	puts("      -/%H%+;-,    +##############/          ");
	puts("         .:$M###MH$%+############X  ,--=;-   ");
	puts("             -/H#####################H+=.    ");
	puts("                .+#################X.        ");
	puts("              =%M####################H;.     ");
	puts("                 /@###############+;;/%%;,   ");
	puts("              -%###################$.        ");
	puts("            ;H######################M=       ");
	puts("         ,%#####MH$%;+#####M###-/@####%      ");
	puts("       :$H%+;=-      -####X.,H#   -+M##@-    ");
	puts("      .              ,###;    ;      =$##+   ");
	puts("                     .#H,               :XH, ");
	puts("                      +                   .;-");
	gotoxy(24, 10);

	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("d");

	gotoxy(0, 14);
	puts("                      =/;;/-                 ");
	puts("                     +:    //                ");
	puts("                    /;      /;               ");
	puts("                   -X        H.              ");
	puts("     .//;;;:;;-,   X=        :+   .-;:=;:;%;.");
	puts("     M-       ,=;;;#:,      ,:#;;:=,       ,@");
	puts("     :%           :%.=/++++/=.$=           %=");
	puts("      ,%;         %/:+/;,,/++:+/         ;+. ");
	puts("        ,+/.    ,;@+,        ,%H;,    ,/+,   ");
	puts("           ;+;;/= @.  .H##X   -X :///+;      ");
	puts("           ;+=;;;.@,  .XM@$.  =X.//;=%/.     ");
	puts("        ,;:      :@%=        =$H:     .+%-   ");
	puts("      ,%=         %;-///==///-//         =%, ");
	puts("     ;+           :%-;;;:;;;;-X-           +:");
	puts("     @-      .-;;;;M-        =M/;;;-.      -X");
	puts("      :;;::;;-.    %-        :+    ,-;;-;:== ");
	puts("                   ,X        H.              ");
	puts("                    ;/      %=               ");
	puts("                     //    +;                ");
	puts("                      ,////,                 ");
	gotoxy(0, 11);

	Sleep(600);
	printf("F");					// for the people who are still alive.
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".");

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,               ");
	puts("               . :H@@@MM@M#H/.,+%;,          ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,       ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-     ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.   ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.  ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;  ");
	puts("      =-./@M@M$                  .;@MMMM@MM: ");
	puts("      X@/ -$MM/                    .+MM@@@M$ ");
	puts("     ,@M@H: :@:                    . =X#@@@@-");
	puts("     ,@@@MMX, .                    /H- ;@M@M=");
	puts("     .H@@@@M@+,                    %MM+..%#$.");
	puts("      /MMMM@MMH/.                  XM@MH; =; ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,  ");
	puts("        .=--------.           -%H.,@@@@@MX,  ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.   ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=     ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=       ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,         ");
	puts("                    =++%%%%+/:-.             ");
	textcolor(14);
	gotoxy(0, 12);

	Sleep(5100);
	system("cls");

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,               ");
	puts("               . :H@@@MM@M#H/.,+%;,          ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,       ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-     ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.   ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.  ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;  ");
	puts("      =-./@M@M$                  .;@MMMM@MM: ");
	puts("      X@/ -$MM/                    .+MM@@@M$ ");
	puts("     ,@M@H: :@:                    . =X#@@@@-");
	puts("     ,@@@MMX, .                    /H- ;@M@M=");
	puts("     .H@@@@M@+,                    %MM+..%#$.");
	puts("      /MMMM@MMH/.                  XM@MH; =; ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,  ");
	puts("        .=--------.           -%H.,@@@@@MX,  ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.   ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=     ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=       ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,         ");
	puts("                    =++%%%%+/:-.             ");
	textcolor(14);
	gotoxy(0, 0);

	Sleep(2300);
	printf("G");					// go ahead and leave me
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".\n");
	Sleep(2450);
	printf("I");					// i think i prefer
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf(" ");
	Sleep(1000);
	printf("t");					//to stay
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("y");
	Sleep(500);
	printf(" ");
	Sleep(60);
	printf("i");					// inside
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".\n");
	Sleep(2300);
	printf("M");					// maybe you'll find someone else to help you.
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("p");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf(". \n");
	Sleep(4200);
	printf("M");					//Maybe Black Mesa...
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("b");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("B");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("M");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("a");

	gotoxy(0, 14);
	textcolor(8);
	puts("                .-;+$XHHHHHHX$+;-.           ");
	puts("             ,;X@@X%/;=----=:/%X@@X/,        ");
	puts("           =$@@%=.              .=+H@X:      ");
	puts("         -XMX:                      =XMX=    ");
	puts("        /@@:                          =H@+   ");
	puts("       %@X,                            .$@$  ");
	puts("      +@X.                               $@% ");
	puts("     -@@,                                .@@=");
	puts("     %@%                                  +@$");
	puts("     H@:                                  :@H");
	puts("     H@:         :HHHHHHHHHHHHHHHHHHX,    =@H");
	puts("     %@%         ;@M@@@@@@@@@@@@@@@@@H-   +@$");
	puts("     =@@,        :@@@@@@@@@@@@@@@@@@@@@= .@@:");
	puts("      +@X        :@@@@@@@@@@@@@@@M@@@@@@:%@% ");
	puts("       $@$,      ;@@@@@@@@@@@@@@@@@M@@@@@@$. ");
	puts("        +@@HHHHHHH@@@@@@@@@@@@@@@@@@@@@@@+   ");
	puts("         =X@@@@@@@@@@@@@@@@@@@@@@@@@@@@X=    ");
	puts("           :$@@@@@@@@@@@@@@@@@@@M@@@@$:      ");
	puts("             ,;$@@@@@@@@@@@@@@@@@@X/-        ");
	puts("                .-;+$XXHHHHHX$+;-.           ");
	textcolor(14);
	gotoxy(16, 3);

	Sleep(500);
	printf(". ");
	Sleep(500);
	printf(". ");
	Sleep(500);
	printf(".\n");
	Sleep(1620);
	printf("T");					//THAT WAS A JOKE.
	Sleep(60);
	printf("H");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf("T");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("W");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf("S");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("J");
	Sleep(60);
	printf("O");
	Sleep(60);
	printf("K");
	Sleep(60);
	printf("E");
	Sleep(60);
	printf(".");
	Sleep(600);
	printf(" ");					// HA HA,
	Sleep(60);
	printf("H");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("H");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf(",");
	Sleep(500);
	printf(" ");
	Sleep(60);
	printf("F");					//FAT CHANCE.
	Sleep(60);
	printf("A");
	Sleep(60);
	printf("T");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("C");
	Sleep(60);
	printf("H");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf("N");
	Sleep(60);
	printf("C");
	Sleep(60);
	printf("E");
	Sleep(60);
	printf(". \n");
	Sleep(2000);
	printf("A");					//Anyway this cake is great
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("y");
	Sleep(60);
	printf(",");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(":");

	gotoxy(0, 14);
	textcolor(7);
	puts("                 ,:/+/-                      ");
	puts("                 /M/              .,-=;//;-  ");
	puts("            .:/= ;MH/,    ,=/+%$XH@MM#@:     ");
	puts("           -$##@+$###@H@MMM#######H:.    -/H#");
	puts("      .,H@H@ X######@ -H#####@+-     -+H###@ ");
	puts("       .,@##H;      +XM##M/,     =%@###@X;-  ");
	puts("     X%-  :M##########$.    .:%M###@%:       ");
	puts("     M##H,   +H@@@$/-.  ,;$M###@%,          -");
	puts("     M####M=,,---,.-%%H####M$:          ,+@##");
	puts("     @##################@/.         :%H##@$- ");
	puts("     M###############H,         ;HM##M$=     ");
	puts("     #################.    .=$M##M$=         ");
	puts("     ################H..;XM##M$=          .:+");
	puts("     M###################@%=           =+@MH%");
	puts("     @################M/.          =+H#X%=   ");
	puts("     =+M##############M,       -/X#X+;.      ");
	puts("       .;XM##########H=    ,/X#H+:,          ");
	puts("          .=+HM######M+/+HM@+=.              ");
	puts("              ,:/%XM####H/.                  ");
	puts("                   ,.:=-.                    ");
	textcolor(14);
	gotoxy(0, 6);

	Sleep(1650);
	printf("I");					//It's so delicous and moist
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("u");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(".\n\n");
	Sleep(700);
	printf("L");					//Look at me still talking when there's science to do.
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("k");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("g");

	gotoxy(0, 14);
	textcolor(7);
	puts("            #+ @      # #              M#@   ");
	puts("      .    .X  X.%##@;# #   +@#######X. @#%  ");
	puts("        ,==.   ,######M+  -#####%M####M-    #");
	puts("       :H##M%:=##+ .M##M,;#####/+#######% ,M#");
	puts("      .M########=  =@#@.=#####M=M#######=  X#");
	puts("      :@@MMM##M.  -##M.,#######M#######. =  M");
	puts("                  @##..###:.    .H####. @@ X,");
	puts("        ############: ###,/####;  /##= @#. M ");
	puts("                ,M## ;##,@#M;/M#M  @# X#% X# ");
	puts("     .%=   ######M## ##.M#:   ./#M ,M #M ,#$ ");
	puts("     ##/         $## #+;#: #### ;#/ M M- @# :");
	puts("     #+ #M@MM###M-;M #:$#-##$H# .#X @ + $#. #");
	puts("           ######/.: #%=# M#:MM./#.-#  @#: H#");
	puts("     +,.=   @###: /@ %#,@  ##@X #,-#@.##% .@#");
	puts("     #####+;/##/ @##  @#,+       /#M    . X, ");
	puts("        ;###M#@ M###H .#M-     ,##M  ;@@; ###");
	puts("        .M#M##H ;####X ,@#######M/ -M###$  -H");
	puts("         .M###%  X####H  .@@MM@;  ;@#M@      ");
	puts("           H#M    /@####/      ,++.  / ==-,  ");
	puts("                    ,=/:, .+X@MMH@#H  #####$=");
	textcolor(14);
	gotoxy(24, 8);

	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("w");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("h");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("r");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf(".");

	gotoxy(0, 14);
	puts("                  =+$HM####@H%;,             ");
	puts("               /H###############M$,          ");
	puts("               ,@################+           ");
	puts("                .H##############+            ");
	puts("                  X############/             ");
	puts("                   $##########/              ");
	puts("                    %########/               ");
	puts("                     /X/;;+X/                ");
	puts("                      -XHHX-                 ");
	puts("                     ,######,                ");
	puts("     #############X  .M####M.  X#############");
	puts("     ##############-   -//-   -##############");
	puts("     X##############%,      ,+##############X");
	puts("     -##############X        X##############-");
	puts("      %############%          %############% ");
	puts("       %##########;            ;##########%  ");
	puts("        ;#######M=              =M#######;   ");
	puts("         .+M###@,                ,@###M+.    ");
	puts("            :XH.                  .HX:       ");
	puts("                                             ");
	gotoxy(0, 9);

	Sleep(800);
	printf("W");					//When i look out there it makes me GLaD i'm not you.
	Sleep(65);
	printf("h");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("n");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("I");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("l");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf("k");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf("u");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf("h");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("r");
	Sleep(65);
	printf("e");

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,               ");
	puts("               . :H@@@MM@M#H/.,+%;,          ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,       ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-     ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.   ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.  ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;  ");
	puts("      =-./@M@M$                  .;@MMMM@MM: ");
	puts("      X@/ -$MM/                    .+MM@@@M$ ");
	puts("     ,@M@H: :@:                    . =X#@@@@-");
	puts("     ,@@@MMX, .                    /H- ;@M@M=");
	puts("     .H@@@@M@+,                    %MM+..%#$.");
	puts("      /MMMM@MMH/.                  XM@MH; =; ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,  ");
	puts("        .=--------.           -%H.,@@@@@MX,  ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.   ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=     ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=       ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,         ");
	puts("                    =++%%%%+/:-.             ");
	textcolor(14);
	gotoxy(21, 9);

	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("i");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("m");
	Sleep(65);
	printf("a");
	Sleep(65);
	printf("k");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("s");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("m");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("G");
	Sleep(65);
	printf("L");
	Sleep(65);
	printf("a");
	Sleep(65);
	printf("D");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("I");
	Sleep(65);
	printf("'");
	Sleep(65);
	printf("m");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("n");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("y");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf("u");
	Sleep(65);
	printf(".\n");
	Sleep(900);
	printf("I");					//I've experiments to run there is research to be done
	Sleep(65);
	printf("'");
	Sleep(65);
	printf("v");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("x");
	Sleep(65);
	printf("p");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("r");
	Sleep(65);
	printf("i");
	Sleep(65);
	printf("m");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("n");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf("s");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("r");
	Sleep(65);
	printf("u");
	Sleep(65);
	printf("n");

	gotoxy(0, 14);
	puts("                      =/;;/-                 ");
	puts("                     +:    //                ");
	puts("                    /;      /;               ");
	puts("                   -X        H.              ");
	puts("     .//;;;:;;-,   X=        :+   .-;:=;:;%;.");
	puts("     M-       ,=;;;#:,      ,:#;;:=,       ,@");
	puts("     :%           :%.=/++++/=.$=           %=");
	puts("      ,%;         %/:+/;,,/++:+/         ;+. ");
	puts("        ,+/.    ,;@+,        ,%H;,    ,/+,   ");
	puts("           ;+;;/= @.  .H##X   -X :///+;      ");
	puts("           ;+=;;;.@,  .XM@$.  =X.//;=%/.     ");
	puts("        ,;:      :@%=        =$H:     .+%-   ");
	puts("      ,%=         %;-///==///-//         =%, ");
	puts("     ;+           :%-;;;:;;;;-X-           +:");
	puts("     @-      .-;;;;M-        =M/;;;-.      -X");
	puts("      :;;::;;-.    %-        :+    ,-;;-;:== ");
	puts("                   ,X        H.              ");
	puts("                    ;/      %=               ");
	puts("                     //    +;                ");
	puts("                      ,////,                 ");
	gotoxy(23, 10);

	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf("h");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("r");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("i");
	Sleep(65);
	printf("s");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("r");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("s");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("a");
	Sleep(65);
	printf("r");
	Sleep(65);
	printf("c");
	Sleep(65);
	printf("h");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("b");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("d");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf("n");
	Sleep(65);
	printf("e");

	gotoxy(0, 14);
	puts("                 .+                          ");
	puts("                  /M;                        ");
	puts("                   H#@:              ;,      ");
	puts("                   -###H-          -@/       ");
	puts("                    %####$.  -;  .%#X        ");
	puts("                     M#####+;#H :M#M.        ");
	puts("     ..          .+/;%#########X###-         ");
	puts("      -/%H%+;-,    +##############/          ");
	puts("         .:$M###MH$%+############X  ,--=;-   ");
	puts("             -/H#####################H+=.    ");
	puts("                .+#################X.        ");
	puts("              =%M####################H;.     ");
	puts("                 /@###############+;;/%%;,   ");
	puts("              -%###################$.        ");
	puts("            ;H######################M=       ");
	puts("         ,%#####MH$%;+#####M###-/@####%      ");
	puts("       :$H%+;=-      -####X.,H#   -+M##@-    ");
	puts("      .              ,###;    ;      =$##+   ");
	puts("                     .#H,               :XH, ");
	puts("                      +                   .;-");
	gotoxy(0, 11);

	Sleep(700);
	printf("O");					//On the people who are still alive
	Sleep(65);
	printf("n");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf("h");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("p");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf("p");
	Sleep(65);
	printf("l");
	Sleep(65);
	printf("e");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("w");
	Sleep(65);
	printf("h");
	Sleep(65);
	printf("o");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("a");
	Sleep(65);
	printf("r");
	Sleep(65);
	printf("e");

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,               ");
	puts("               . :H@@@MM@M#H/.,+%;,          ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,       ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-     ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.   ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.  ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;  ");
	puts("      =-./@M@M$                  .;@MMMM@MM: ");
	puts("      X@/ -$MM/                    .+MM@@@M$ ");
	puts("     ,@M@H: :@:                    . =X#@@@@-");
	puts("     ,@@@MMX, .                    /H- ;@M@M=");
	puts("     .H@@@@M@+,                    %MM+..%#$.");
	puts("      /MMMM@MMH/.                  XM@MH; =; ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,  ");
	puts("        .=--------.           -%H.,@@@@@MX,  ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.   ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=     ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=       ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,         ");
	puts("                    =++%%%%+/:-.             ");
	textcolor(14);
	gotoxy(21, 11);

	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("s");
	Sleep(65);
	printf("t");
	Sleep(65);
	printf("i");
	Sleep(65);
	printf("l");
	Sleep(65);
	printf("l");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("a");
	Sleep(65);
	printf("l");
	Sleep(65);
	printf("i");
	Sleep(65);
	printf("v");
	Sleep(65);
	printf("e");
	Sleep(1300);
	system("cls");

	gotoxy(0, 14);
	textcolor(11);
	puts("                   .,-:;//;:=,               ");
	puts("               . :H@@@MM@M#H/.,+%;,          ");
	puts("            ,/X+ +M@@M@MM%=,-%HMMM@X/,       ");
	puts("          -+@MM; $M@@MH+-,;XMMMM@MMMM@+-     ");
	puts("         ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.   ");
	puts("       ,%MM@@MH ,@%=            .---=-=:=,.  ");
	puts("       =@#@@@MX .,              -%HX$$%%%+;  ");
	puts("      =-./@M@M$                  .;@MMMM@MM: ");
	puts("      X@/ -$MM/                    .+MM@@@M$ ");
	puts("     ,@M@H: :@:                    . =X#@@@@-");
	puts("     ,@@@MMX, .                    /H- ;@M@M=");
	puts("     .H@@@@M@+,                    %MM+..%#$.");
	puts("      /MMMM@MMH/.                  XM@MH; =; ");
	puts("       /%+%$XHH@$=              , .H@@@@MX,  ");
	puts("        .=--------.           -%H.,@@@@@MX,  ");
	puts("        .%MM@@@HHHXX$$$%+- .:$MMX =M@@MM%.   ");
	puts("          =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=     ");
	puts("            =%@M@M#@$-.=$@MM@@@M; %M%=       ");
	puts("              ,:+$+-,/H#MMMMMMM@= =,         ");
	puts("                    =++%%%%+/:-.             ");
	textcolor(14);
	gotoxy(0, 0);

	Sleep(700);
	printf("A");					// And belive me i am
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" b");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf(" \n");
	Sleep(600);
	printf("s");					//still alive
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".\n\n");
	Sleep(1400);
	printf("I");					//I'm doing science and i'm
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf("o");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("g");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("s");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("c");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf(" \n");
	Sleep(400);
	printf("s");					//still alive
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".\n\n");
	Sleep(1500);
	printf("I");					//I feel FANTASTIC and I'm
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("f");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("F");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf("N");
	Sleep(60);
	printf("T");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf("S");
	Sleep(60);
	printf("T");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf("C");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("n");
	Sleep(60);
	printf("d");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf("'");
	Sleep(60);
	printf("m");
	Sleep(60);
	printf(" \n");
	Sleep(400);
	printf("s");					//still alive
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".\n\n");
	Sleep(1650);
	printf("W");					//While you're dying i'll be
	Sleep(45);
	printf("h");
	Sleep(45);
	printf("i");
	Sleep(45);
	printf("l");
	Sleep(45);
	printf("e");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("y");
	Sleep(45);
	printf("o");
	Sleep(45);
	printf("u");
	Sleep(45);
	printf("'");
	Sleep(45);
	printf("r");
	Sleep(45);
	printf("e");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("d");
	Sleep(45);
	printf("y");
	Sleep(45);
	printf("i");
	Sleep(45);
	printf("n");
	Sleep(45);
	printf("g");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("I");
	Sleep(45);
	printf("'");
	Sleep(45);
	printf("l");
	Sleep(45);
	printf("l");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("b");
	Sleep(45);
	printf("e");
	Sleep(45);
	printf(" \n");
	Sleep(530);
	printf("s");					//still alive
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".\n\n");
	Sleep(1450);
	printf("A");					//And when you're dead i will be
	Sleep(45);
	printf("n");
	Sleep(45);
	printf("d");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("w");
	Sleep(45);
	printf("h");
	Sleep(45);
	printf("e");
	Sleep(45);
	printf("n");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("y");
	Sleep(45);
	printf("o");
	Sleep(45);
	printf("u");
	Sleep(45);
	printf("'");
	Sleep(45);
	printf("r");
	Sleep(45);
	printf("e");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("d");
	Sleep(45);
	printf("e");
	Sleep(45);
	printf("a");
	Sleep(45);
	printf("d");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("I");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("w");
	Sleep(45);
	printf("i");
	Sleep(45);
	printf("l");
	Sleep(45);
	printf("l");
	Sleep(45);
	printf(" ");
	Sleep(45);
	printf("b");
	Sleep(45);
	printf("e");
	Sleep(45);
	printf(" \n");
	Sleep(560);
	printf("s");					//still alive
	Sleep(60);
	printf("t");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("a");
	Sleep(60);
	printf("l");
	Sleep(60);
	printf("i");
	Sleep(60);
	printf("v");
	Sleep(60);
	printf("e");
	Sleep(60);
	printf(".");
	Sleep(1150);
	system("cls");

	printf("\nS");					//still alive
	Sleep(60);
	printf("T");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf("L");
	Sleep(60);
	printf("L");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf("L");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf("V");
	Sleep(60);
	printf("E");
	Sleep(60);
	printf(".\n\n");
	Sleep(1300);
	printf("S");					//still alive
	Sleep(60);
	printf("T");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf("L");
	Sleep(60);
	printf("L");
	Sleep(60);
	printf(" ");
	Sleep(60);
	printf("A");
	Sleep(60);
	printf("L");
	Sleep(60);
	printf("I");
	Sleep(60);
	printf("V");
	Sleep(60);
	printf("E");
	Sleep(60);
	printf(".");
	Sleep(1500);
	//--------------------------------------------------------------------------------------------

	gotoxy(33, 14);
	printf("T");					//THANK YOU FOR CONTRIBUTED
	Sleep(65);
	printf("H");
	Sleep(65);
	printf("A");
	Sleep(65);
	printf("N");
	Sleep(65);
	printf("K");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("Y");
	Sleep(65);
	printf("O");
	Sleep(65);
	printf("U");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("F");
	Sleep(65);
	printf("O");
	Sleep(65);
	printf("R");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("C");
	Sleep(65);
	printf("O");
	Sleep(65);
	printf("N");
	Sleep(65);
	printf("T");
	Sleep(65);
	printf("R");
	Sleep(65);
	printf("I");
	Sleep(65);
	printf("B");
	Sleep(65);
	printf("U");
	Sleep(65);
	printf("T");
	Sleep(65);
	printf("E");
	Sleep(65);
	printf("D\n");
	Sleep(65);
	gotoxy(33, 15);
	printf("T");					//TO THIS
	Sleep(65);
	printf("O");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("T");
	Sleep(65);
	printf("H");
	Sleep(65);
	printf("I");
	Sleep(65);
	printf("S");
	Sleep(65);
	gotoxy(33, 16);
	printf("E");					//ENRICHED TEAM PROJECT!!
	Sleep(65);
	printf("N");
	Sleep(65);
	printf("R");
	Sleep(65);
	printf("I");
	Sleep(65);
	printf("C");
	Sleep(65);
	printf("H");
	Sleep(65);
	printf("E");
	Sleep(65);
	printf("D");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("T");
	Sleep(65);
	printf("E");
	Sleep(65);
	printf("A");
	Sleep(65);
	printf("M");
	Sleep(65);
	printf(" ");
	Sleep(65);
	printf("P");
	Sleep(65);
	printf("R");
	Sleep(65);
	printf("O");
	Sleep(65);
	printf("J");
	Sleep(65);
	printf("E");
	Sleep(65);
	printf("C");
	Sleep(65);
	printf("T");
	Sleep(65);
	printf("!");
	Sleep(65);
	printf("!");
	Sleep(3250);
	system("cls");
	textcolor(15);

	timeEndPeriod(1);		// 설정된 주기를 해제
	return;
}

/*  제작자: Lulin Pollux (Team Project member) */
/*  MIT License
	해당 C코드파일(.c)은 MIT License에 따라 이용할 수 있습니다. */